format_version: v1.0
configName: LE00Sercom
folderName: LE00Sercom
frameworkPath: C:\Harmony
processor: PIC32CM5164LE00064
projectName: LE00Sercom
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CM-LE_DFP\1.1.162\atdf\PIC32CM5164LE00064.atdf
