format_version: v1.0
configName: Sercom
folderName: Sercom_NonSecure
frameworkPath: C:\Harmony
processor: PIC32CM5164LS00064
projectName: Sercom_NonSecure
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'true'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CM-LS_DFP\1.1.162\PIC32CM-LS00\atdf\PIC32CM5164LS00064.atdf
